export enum NotificationType {
  ORDER_UPDATED = 'ORDER_UPDATED',
  ORDER_CREATED = 'ORDER_CREATED',
  PAYMENT_SUCCESS = 'PAYMENT_SUCCESS',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  SYSTEM = 'SYSTEM',
  BROADCAST = 'BROADCAST',
}
